/**
 * Panel component with Chakra UI
 * Replaces PanelWithHeader from PanelComponents.tsx
 */

import React from 'react'
import { Box, Collapse, useDisclosure, type BoxProps } from '@chakra-ui/react'
import { PanelHeader } from './PanelHeader'
import { RenderCountBadgeWrapper } from './RenderCountBadgeWrapper'
import { useSidebarPanelState } from '../contexts/sidebarPanelState'
import { AutoPanelKeyContext, useAutoPanelKeyContext } from '../contexts/autoPanelKeyContext'
import { panelSpacing } from '../theme/spacing'
import { useThemeColors } from '../hooks/useThemeColors'

export interface PanelProps extends BoxProps {
  /** Icon to display in header */
  icon?: React.ReactNode
  /** Panel title */
  title?: string
  /** Hide header (title & icon) entirely */
  hideHeader?: boolean
  /** Panel content */
  children: React.ReactNode
  /** Optional actions in header (e.g., badges, buttons) */
  headerActions?: React.ReactNode
  /** Whether panel should be open by default */
  defaultOpen?: boolean
  /** Whether panel can be collapsed */
  isCollapsible?: boolean
  /** Whether panel supports maximize/minimize */
  isMaximizable?: boolean
  /** Optional stable key for the panel - when provided, only one panel with a key can be open at a time */
  panelKey?: string
  /** Show render count badge (debug only) */
  showRenderCount?: boolean
  /** Disable the open-state outer frame when the panel is expanded */
  disableExpandedFrame?: boolean
}

export const Panel: React.FC<PanelProps> = ({
  icon,
  title,
  hideHeader = false,
  children,
  headerActions,
  defaultOpen = true,
  isCollapsible = true,
  isMaximizable = false,
  panelKey,
  showRenderCount = import.meta.env.DEV,
  disableExpandedFrame = false,
  ...boxProps
}) => {
  const { isOpen, onToggle } = useDisclosure({ defaultIsOpen: defaultOpen })
  const { openPanelKey, setOpenPanelKey, maximizedPanelKey, setMaximizedPanelKey } = useSidebarPanelState();
  const { namespace: autoPanelKeyNamespace, depth: autoPanelKeyDepth } = useAutoPanelKeyContext();
  const { panelContainer: { openFrameShadow } } = useThemeColors();

  const autoGeneratedPanelKey =
    panelKey === undefined &&
    autoPanelKeyNamespace &&
    typeof title === 'string' &&
    title.trim().length > 0 &&
    autoPanelKeyDepth === 0
      ? `${autoPanelKeyNamespace}:${title.trim().toLowerCase().replace(/\s+/g, '-')}`
      : undefined;

  const resolvedPanelKey = panelKey ?? autoGeneratedPanelKey;

  // Panels opt into the shared "only one open at a time" behavior either by
  // passing an explicit panelKey or by receiving an auto-generated key from a section scope.
  const usesGlobalCollapseState = resolvedPanelKey !== undefined;

  const isCurrentlyMaximized = resolvedPanelKey ? maximizedPanelKey === resolvedPanelKey : false;

  // When using global collapse state, compute isOpen from store
  const computedIsOpen = usesGlobalCollapseState && openPanelKey != null
    ? openPanelKey === resolvedPanelKey
    : isOpen;

  const effectiveIsOpen = computedIsOpen;
  const showOpenFrame = isCollapsible && effectiveIsOpen && !isCurrentlyMaximized && !disableExpandedFrame;
  const openFrameAnimationName = 'panelOpenGlowRise';

  // When using global collapse state, toggle changes which panel is open
  const computedOnToggle = usesGlobalCollapseState && resolvedPanelKey
    ? () => {
        if (openPanelKey === resolvedPanelKey) {
          setOpenPanelKey(null); // Close current panel
        } else {
          setOpenPanelKey(resolvedPanelKey); // Open this panel, close others
        }
      }
    : onToggle;

  const handleMaximize = () => {
    if (!resolvedPanelKey) return;
    setMaximizedPanelKey(resolvedPanelKey);
  };

  const handleMinimize = () => {
    setMaximizedPanelKey(null);
  };

  const containerFlexProps: BoxProps = isCurrentlyMaximized
    ? { display: 'flex', flexDirection: 'column', flex: 1, minH: 0 }
    : {};

  const maximizedContentProps: BoxProps = isCurrentlyMaximized
    ? { flex: 1, display: 'flex', flexDirection: 'column', minH: 0, overflowY: 'auto' }
    : {};

  const childAutoPanelKeyContext = React.useMemo(() => {
    if (!autoPanelKeyNamespace) {
      return { namespace: null, depth: 0 };
    }

    const createsAutoKeyBoundary =
      resolvedPanelKey !== undefined ||
      (typeof title === 'string' && title.trim().length > 0);

    if (!createsAutoKeyBoundary) {
      return {
        namespace: autoPanelKeyNamespace,
        depth: autoPanelKeyDepth,
      };
    }

    return {
      namespace: autoPanelKeyNamespace,
      depth: autoPanelKeyDepth + 1,
    };
  }, [autoPanelKeyDepth, autoPanelKeyNamespace, resolvedPanelKey, title]);

  return (
    <AutoPanelKeyContext.Provider value={childAutoPanelKeyContext}>
      <Box
        data-panel-open={showOpenFrame ? 'true' : undefined}
        position="relative"
        mt={panelSpacing.betweenPanels}
        borderRadius="lg"
        isolation="isolate"
        css={{
          [`@keyframes ${openFrameAnimationName}`]: {
            '0%': {
              opacity: 0,
              transform: 'translateY(4px) scale(0.985)',
              boxShadow: 'none',
            },
            '45%': {
              opacity: 0,
              transform: 'translateY(3px) scale(0.992)',
              boxShadow: 'none',
            },
            '100%': {
              opacity: 1,
              transform: 'translateY(-2px) scale(1)',
              boxShadow: openFrameShadow,
            },
          },
        }}
        _before={{
          content: '""',
          position: 'absolute',
          inset: { base: '-3px -3px', md: '-4px -4px' },
          borderRadius: '10px',
          boxShadow: showOpenFrame ? openFrameShadow : 'none',
          opacity: showOpenFrame ? 1 : 0,
          transform: showOpenFrame ? 'translateY(-2px) scale(1)' : 'translateY(2px) scale(0.985)',
          animation: showOpenFrame
            ? `${openFrameAnimationName} 360ms cubic-bezier(0.2, 0.8, 0.2, 1) 90ms both`
            : 'none',
          transition: 'opacity 0.18s ease, transform 0.18s ease, box-shadow 0.18s ease',
          pointerEvents: 'none',
        }}
        {...containerFlexProps}
        {...boxProps}
      >
        {showRenderCount && (
          <RenderCountBadgeWrapper componentName={`Panel: ${title || 'Untitled'}`} position="top-left" />
        )}
        
        {!hideHeader && (icon || title) && (
          <PanelHeader
            icon={icon}
            title={title}
            actions={headerActions}
            isCollapsible={isCollapsible}
            isOpen={effectiveIsOpen}
            onToggle={computedOnToggle}
            isMaximizable={isMaximizable}
            isMaximized={isCurrentlyMaximized}
            onMaximize={handleMaximize}
            onMinimize={handleMinimize}
          />
        )}
        
        {isCollapsible ? (
          <Collapse
            in={effectiveIsOpen}
            animateOpacity
            style={isCurrentlyMaximized ? { height: '100%', display: 'flex', flexDirection: 'column', minHeight: 0 } : undefined}
          >
            <Box {...maximizedContentProps}>
              {children}
            </Box>
          </Collapse>
        ) : (
          <Box {...maximizedContentProps}>
            {children}
          </Box>
        )}
      </Box>
    </AutoPanelKeyContext.Provider>
  )
}
